cluster.name: "elasticsearch"

node.master: true

node.data: true

http.port: 9200

discovery.zen.ping.unicast.hosts: "elasticsearch"

network.publish_host: elasticsearch

network.bind_host: 0.0.0.0

http.cors.enabled: true

http.cors.allow-origin: "*"

discovery.zen.minimum_master_nodes: 1

bootstrap.memory_lock: true