cluster.name: "elasticsearch"

node.master: true

node.data: true

node.name: "node-3"

http.port: 9202

transport.tcp.port: 9302

discovery.zen.ping.unicast.hosts: ["node-1:9300", "node-2:9301", "node-3:9302"]

network.publish_host: node-1

network.bind_host: "0.0.0.0"

http.cors.enabled: true

http.cors.allow-origin: "*"

discovery.zen.minimum_master_nodes: 2