cluster.name: "elasticsearch"

node.master: true

node.data: true

node.name: "node-2"

# http.port: 9201
#
# transport.tcp.port: 9301

discovery.zen.ping.unicast.hosts: [elasticsearch-1, elasticsearch-2, elasticsearch-3]

network.publish_host: elasticsearch-2

network.bind_host: "0.0.0.0"

http.cors.enabled: true

http.cors.allow-origin: "*"

discovery.zen.minimum_master_nodes: 2
