version: '2'

services:
  # ElasticSearch node 1 server
  elasticsearch:
    tty: true
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/node_1.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/$NODE_1_NAME:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      bootstrap.memory_lock: "true"
    container_name: elasticsearch
    networks:
      elk:
        ipv4_address: $NODE_1_IP
    stdin_open: true
    links:
      - elasticsearch2
      - elasticsearch3
      - kibana
    ulimits:
      memlock:
        soft: -1
        hard: -1
    extra_hosts:
      - "${NODE_1_NAME}:${NODE_1_IP}"
      - "${NODE_2_NAME}:${NODE_2_IP}"
      - "${NODE_3_NAME}:${NODE_3_IP}"
      - "${KIBANA_NAME}:${KIBANA_IP}"

  #ElasticSearch node 2 server
  elasticsearch2:
    tty: true
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/node_2.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/$NODE_2_NAME:/usr/share/elasticsearch/data:rw
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      bootstrap.memory_lock: "true"
    container_name: elasticsearch2
    networks:
      elk:
        ipv4_address: $NODE_2_IP
    stdin_open: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    extra_hosts:
      - "${NODE_1_NAME}:${NODE_1_IP}"
      - "${NODE_2_NAME}:${NODE_2_IP}"
      - "${NODE_3_NAME}:${NODE_3_IP}"
      - "${KIBANA_NAME}:${KIBANA_IP}"

  #ElasticSearch node 3 server
  elasticsearch3:
    tty: true
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/node_3.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/$NODE_3_NAME:/usr/share/elasticsearch/data:rw
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      bootstrap.memory_lock: "true"
    container_name: elasticsearch3
    networks:
      elk:
        ipv4_address: $NODE_3_IP
    stdin_open: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    extra_hosts:
      - "${NODE_1_NAME}:${NODE_1_IP}"
      - "${NODE_2_NAME}:${NODE_2_IP}"
      - "${NODE_3_NAME}:${NODE_3_IP}"
      - "${KIBANA_NAME}:${KIBANA_IP}"

  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.3.2'
    container_name: kibana
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      elk:
        ipv4_address: $KIBANA_IP
    extra_hosts:
      - "${NODE_1_NAME}:${NODE_1_IP}"
      - "${NODE_2_NAME}:${NODE_2_IP}"
      - "${NODE_3_NAME}:${NODE_3_IP}"
      - "${KIBANA_NAME}:${KIBANA_IP}"

  headPlugin:
      image: 'mobz/elasticsearch-head:5'
      container_name: head
      ports:
        - '9100:9100'
      networks:
        elk:
          ipv4_address: $ELASTIC_HEAD_IP
      extra_hosts:
      - "${NODE_1_NAME}:${NODE_1_IP}"
      - "${NODE_2_NAME}:${NODE_2_IP}"
      - "${NODE_3_NAME}:${NODE_3_IP}"
      - "${KIBANA_NAME}:${KIBANA_IP}"

networks:
  elk:
    driver: bridge
    ipam:
      config:
        - subnet: $SUB_NET
          gateway: $GATEWAY
